### PR TITLE
First Index.html

### PR DESCRIPTION
**Pull request by sndrgrdn**
First PR

### CODE REVIEW

**Comment by inooid** [comment]
:+1:

**Comment by MaximilianLloyd** [comment]
:+1:

**Comment by inooid** [comment]
Can we add this to the `src` folder? So we have all the source files in one folder?

**Comment by sndrgrdn** [comment]
Shall i put it in `src/app` ?

**Comment by inooid** [comment]
Honestly I think `src` is fine, but it's ok! :joy:

**Comment by inooid** [comment]
:+1:

**Pull request merged**
